---
# $ buildah pull $BASE_IMAGE
# $ buildah from --name $CONT_NAME $BASE_IMAGE
# $ printf "$CONT_NAME \
#   ansible_connection=buildah \
#   ansible_python_interpreter=/usr/bin/python3" >inventory-container
# $ ansible-playbook -i inventory-container -c buildah ./recipe.yaml
# $ buildah commit --cmd '/entrypoint.sh' $CONT_NAME my-fancy-image
# $ buildah rm $(CONT_NAME)

# [] Add variable checking 

- block: 
  - name: Gather facts from buildah_build_host
    setup:
    delegate_facts: true

  - name: Copy needed facts buildah_build_host
    set_fact:
      ansible_os_family: "{{hostvars[buildah_build_host]['ansible_os_family']}}"
      ansible_date_time: "{{hostvars[buildah_build_host]['ansible_date_time']}}"
      ansible_distribution: "{{hostvars[buildah_build_host]['ansible_distribution']}}"
      ansible_distribution_version: "{{hostvars[buildah_build_host]['ansible_distribution_version']}}"
      ansible_distribution_major_version: "{{hostvars[buildah_build_host]['ansible_distribution_major_version']}}"
      ansible_architecture: "{{hostvars[buildah_build_host]['ansible_architecture']}}"

  - name: Override facts
    set_fact: "{{ item.key }}={{ item.value }}"
    when: item.value is defined and item.value != ""
    with_items: "{{ buildah_fact_override|dict2items }}"

  - name: Set OS dependent variables
    include_vars: "{{lookup('first_found', params)}}"
    vars:
      params:
        files:
          - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
          - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
        paths:
          - 'vars'


  - name: Pull image
    command: buildah pull "{{ buildah_base_image }}"
  
  - name: Create image from base
    command: buildah from --name "{{ buildah_working_name }}" "{{ buildah_base_image }}"
  delegate_to: "{{ buildah_build_host }}"

- name: Override the buildah container name
  set_fact:
    ansible_host: "{{ buildah_working_name }}"

- name: Ensure Python is installed
  raw: zypper -n install --no-recommends python3
